### ISSUE TITLE
KeePassXC Firefox integration is incompatible with Firefox Snap

### ISSUE THREAD

**Issue by ricktimmis** [kfocus/kfocus-source#2] opened 2023-01-21 14:20 UTC
**Describe the bug**
KeePassXC does not support browser integration with Firefox, because it is installed via Snap

**To Reproduce**
1. Open KeePassXC -> Setting -> Browser Integrations and enable Integration for Firefox
2. Open Firefox and Install the KeePassXC Addon
3. Attempt to 'Reload' the connection via the Firefox addon
4. On the very first attempt a Plasma Dialog appears request the user to grant access to the messaging bus.
5. Clicking OK to the Plasma Dialog,appears to enable permission and the dialog does not appear again
6. In KeePassXC settings it states integration with Snap installed Firefox is not supported (Probably Snap Confinement Issue)

**Expected behavior**
KeePassXC and Firefox both ship as default with Kubuntu Focus, it is expect that the integration should work seamlessly 'out of the box'

**Screenshots**
![image](https://user-images.githubusercontent.com/8983149/213870447-888c67d8-cc24-4c90-9b99-8cce28c820f2.png)

![image](https://user-images.githubusercontent.com/8983149/213870490-e283a62c-1908-4082-8406-289bab364fae.png)

**Desktop (please complete the following information):**
 - OS:  Kubuntu Focus 22.04
 - Firefox

**Additional context**

The following post provides a step by step guide to removing Firefox as a Snap, and installing the Mozilla Team build from the PPA. It also includes instructions for Package Pinning, and Auto Update preferences.

https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04

Hopefully, the above could be added into the KFocus build scripts.

**Comment by ricktimmis** [comment] 2023-01-21 14:22
I can confirm that those Fix steps worked perfectly, and Firefox KeePassXC integration is working as expected. HTH

**Comment by eeickmeyer** [comment] 2023-01-21 14:27
This is fixed in the latest Firefox Snap and is not a bug with Kubuntu Focus. See https://discourse.ubuntu.com/t/call-for-testing-native-messaging-support-in-the-firefox-snap/29759/105?u=d0od.

**Closed as completed by eeickmeyer** 2023-01-21 14:27 UTC
Labels: enhancement, good first issue

**Comment by ricktimmis** [comment] 2023-01-22 09:36
Hiya Eric

Happy New Year, I hope you had a lovely Xmas.
Thanks for being super responsive, on the issue I raised.

I came across that issue yesterday, whilst configuring KeePassXC. My Focus
is a new installation done just over Christmas and Firefox snap was up to
date. Yet it still didn't work for me.
My worry here is that if I was struggling with it not working out of the
box, our users will to.

Of course maybe I missed something, but I had no issue with Chrome. For
Firefox, once I switched the Snap for the PPA it just worked like a charm.

Of course it would be better if the snap just worked. Reading that thread
it mentions about lying to a shell script (screenshot attached), about
browser being installed via Snap. Again, we shouldn't really expect our
users to do that.

I've got another Focus for reinstall soon, I'll test again when I rebuild
it, and let you know how it goes.

Say hi to Mike, and Dana from me

TTFN
Rick

**Comment by mmikowski** [comment] 2023-01-23 06:30
Hi Rick! Thanks for the bug report, and happy new year to you too! Erich, thanks for the research and the response.

We are in a bit of a pickle with Firefox. On one hand, we definitely want everything to work "out of the box"; on the other, the snap has made great progress in speed and memory use, and it is officially supported by Canonical and Kubuntu. Moving away from the snap could result in support challenges, unfortunately.

It looks like this "lying to a shell script" requirement to get KeePassXC to interface with the snap is one of the few remaining rough edges. What if we update the guidance [in the passwords guided solution](https://kfocus.org/wf/passwords.html#bkm_keepassxc)? We could also include a link to that page in the [Curated Apps Page](https://kfocus.org/wf/apps) as well. Would you think that would be a decent compromise?

Any other ideas are certainly welcome!  And thanks again for the bug report.

**Comment by mmikowski** [comment] 2023-08-04 04:25
FYI, the note made it to the the passwords guided solution with the link to the deb version and a link to the comment by Erich.

**Comment by ricktimmis** [comment] 2023-08-05 09:31
Dear Mike

Thanks for updating me.

In other news, the amazing bafoons at the company I work, who decided NOT
to take my considered advice to use Kubuntu Focus laptops.

Apparently felt more comfortable buying HP Windows laptops and asking the
engineers to install Ubuntu.

That's right! They didn't even buy the ones HP ship with Ubuntu installed 😂

Needless to say, they've been having all the problems that Mike told them
about, exactly as it describes in the 'How much is your time worth' video.
It has burned a lot of engineering hours, and needlessly

I want to say 'Thanks again Mike for taking the time to join us remotely
and explain how Kubuntu Focus avoids these issues. Shame they chose not to
listen'

Best Wishes
Rick

**Comment by mmikowski** [comment] 2023-10-20 19:33
Hi Rick: Just cleaning up old notifications, and I was reminded of [this doc which has been out for a while](https://kfocus.org/wf/browsers.html#bkm_firefox) that explains why/when/how a user might switch to a Debian package for Firefox. Of course, for most people, we advocate they stick with the official snap if it works for them.  Cheers!
